# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tell The Sky' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tell The Sky
pod 'Alamofire'

  target 'Tell The SkyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Tell The SkyUITests' do
    # Pods for testing
  end

end
